import { User, Gift, GiftAction, Partner, Sponsor, Notification, FraudFlag, Branch, WeeklyDrop, CommunityPool, PlusOneOffer, Achievement, ACHIEVEMENTS_LIST } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    phone: '+905551234567',
    name: 'Coşkun',
    avatar: undefined,
    birthday: '1990-05-15',
    role: 'user',
    tier: 'free',
    iyikiScore: 12,
    dailySendCount: 0,
    dailySendLimit: 1,
    dailyReceiveCount: 0,
    createdAt: '2026-03-01T10:00:00Z',
    status: 'active',
    notificationPrefs: { push: true, sms: true },
  },
  {
    id: 'user-2',
    phone: '+905559876543',
    name: 'Ayşe',
    role: 'user',
    tier: 'premium',
    iyikiScore: 24,
    dailySendCount: 1,
    dailySendLimit: 3,
    dailyReceiveCount: 0,
    createdAt: '2026-02-15T08:00:00Z',
    status: 'active',
    notificationPrefs: { push: true, sms: true },
  },
  {
    id: 'user-3',
    phone: '+905553456789',
    name: 'Mehmet',
    role: 'user',
    tier: 'free',
    iyikiScore: 8,
    dailySendCount: 0,
    dailySendLimit: 1,
    dailyReceiveCount: 1,
    createdAt: '2026-03-10T14:00:00Z',
    status: 'active',
    notificationPrefs: { push: true, sms: false },
  },
  {
    id: 'admin-1',
    phone: '+905550001111',
    name: 'Admin',
    role: 'admin',
    tier: 'premium',
    iyikiScore: 0,
    dailySendCount: 0,
    dailySendLimit: 99,
    dailyReceiveCount: 0,
    createdAt: '2026-01-01T00:00:00Z',
    status: 'active',
    notificationPrefs: { push: true, sms: true },
  },
  {
    id: 'partner-1',
    phone: '+905550002222',
    name: 'Starbucks Yönetici',
    role: 'partner',
    tier: 'free',
    iyikiScore: 0,
    dailySendCount: 0,
    dailySendLimit: 0,
    dailyReceiveCount: 0,
    createdAt: '2026-01-01T00:00:00Z',
    status: 'active',
    notificationPrefs: { push: true, sms: true },
  },
  {
    id: 'sponsor-1',
    phone: '+905550003333',
    name: 'Garanti BBVA',
    role: 'sponsor',
    tier: 'free',
    iyikiScore: 0,
    dailySendCount: 0,
    dailySendLimit: 0,
    dailyReceiveCount: 0,
    createdAt: '2026-01-01T00:00:00Z',
    status: 'active',
    notificationPrefs: { push: true, sms: true },
  },
];

export const MOCK_PARTNERS: Partner[] = [
  {
    id: 'partner-starbucks',
    name: 'Starbucks',
    logo: '/images/partners/starbucks.svg',
    apiKey: 'sk_starbucks_xxx',
    isActive: true,
    totalGifts: 1250,
    totalRedeemed: 980,
    branches: [
      { id: 'b1', partnerId: 'partner-starbucks', name: 'Starbucks Kadıköy', address: 'Kadıköy Moda Cad. No:15', lat: 40.9903, lng: 29.0242, stockStatus: 'available' },
      { id: 'b2', partnerId: 'partner-starbucks', name: 'Starbucks Bağdat Cad.', address: 'Bağdat Cad. No:245', lat: 40.9634, lng: 29.0688, stockStatus: 'available' },
      { id: 'b3', partnerId: 'partner-starbucks', name: 'Starbucks Beşiktaş', address: 'Beşiktaş Çarşı No:8', lat: 41.0435, lng: 29.0054, stockStatus: 'low' },
    ],
  },
  {
    id: 'partner-migros',
    name: 'Migros',
    logo: '/images/partners/migros.svg',
    apiKey: 'sk_migros_xxx',
    isActive: true,
    totalGifts: 870,
    totalRedeemed: 650,
    branches: [
      { id: 'b4', partnerId: 'partner-migros', name: 'Migros Ataşehir', address: 'Ataşehir Bulvarı No:22', lat: 40.9923, lng: 29.1241, stockStatus: 'available' },
      { id: 'b5', partnerId: 'partner-migros', name: 'Migros Maltepe', address: 'Maltepe Sahil No:5', lat: 40.9354, lng: 29.1322, stockStatus: 'available' },
    ],
  },
  {
    id: 'partner-dr',
    name: 'D&R',
    logo: '/images/partners/dr.svg',
    apiKey: 'sk_dr_xxx',
    isActive: true,
    totalGifts: 430,
    totalRedeemed: 320,
    branches: [
      { id: 'b6', partnerId: 'partner-dr', name: 'D&R Cevahir', address: 'Cevahir AVM Kat:2', lat: 41.0629, lng: 28.9891, stockStatus: 'available' },
    ],
  },
  {
    id: 'partner-ciceksepeti',
    name: 'Çiçeksepeti',
    logo: '/images/partners/ciceksepeti.svg',
    apiKey: 'sk_ciceksepeti_xxx',
    isActive: true,
    totalGifts: 290,
    totalRedeemed: 210,
    branches: [
      { id: 'b7', partnerId: 'partner-ciceksepeti', name: 'Çiçeksepeti Teslimat', address: 'Online Teslimat', lat: 41.0082, lng: 28.9784, stockStatus: 'available' },
    ],
  },
];

export const MOCK_SPONSORS: Sponsor[] = [
  {
    id: 'sponsor-garanti',
    name: 'Garanti BBVA',
    logo: '/images/sponsors/garanti.svg',
    budget: 100000,
    spent: 34500,
    campaignStart: '2026-04-01',
    campaignEnd: '2026-06-30',
    isActive: true,
    giftsSponsoredCount: 2300,
  },
  {
    id: 'sponsor-turkcell',
    name: 'Turkcell',
    logo: '/images/sponsors/turkcell.svg',
    budget: 75000,
    spent: 12000,
    campaignStart: '2026-04-01',
    campaignEnd: '2026-05-31',
    isActive: true,
    giftsSponsoredCount: 800,
  },
];

export const MOCK_GIFTS: Gift[] = [
  {
    id: 'gift-1',
    partnerId: 'partner-starbucks',
    partnerName: 'Starbucks',
    partnerLogo: '/images/partners/starbucks.svg',
    name: 'Latte',
    description: 'Sıcacık bir Starbucks Latte',
    image: '☕',
    category: 'coffee',
    stock: 150,
    expiryHours: 72,
    sponsorId: 'sponsor-garanti',
    sponsorName: 'Garanti BBVA',
    isActive: true,
    isPremium: false,
  },
  {
    id: 'gift-2',
    partnerId: 'partner-migros',
    partnerName: 'Migros',
    partnerLogo: '/images/partners/migros.svg',
    name: 'Tadelle Çikolata',
    description: 'Tadelle sütlü çikolata',
    image: '🍫',
    category: 'chocolate',
    stock: 200,
    expiryHours: 72,
    sponsorId: 'sponsor-garanti',
    sponsorName: 'Garanti BBVA',
    isActive: true,
    isPremium: false,
  },
  {
    id: 'gift-3',
    partnerId: 'partner-dr',
    partnerName: 'D&R',
    partnerLogo: '/images/partners/dr.svg',
    name: 'Küçük Prens',
    description: 'Antoine de Saint-Exupéry - Küçük Prens',
    image: '📖',
    category: 'book',
    stock: 80,
    expiryHours: 72,
    sponsorId: undefined,
    sponsorName: undefined,
    isActive: true,
    isPremium: false,
  },
  {
    id: 'gift-4',
    partnerId: 'partner-ciceksepeti',
    partnerName: 'Çiçeksepeti',
    partnerLogo: '/images/partners/ciceksepeti.svg',
    name: 'Tek Dal Gül',
    description: 'Taze kırmızı gül',
    image: '🌹',
    category: 'flower',
    stock: 50,
    expiryHours: 72,
    sponsorId: 'sponsor-turkcell',
    sponsorName: 'Turkcell',
    isActive: true,
    isPremium: false,
  },
  {
    id: 'gift-5',
    partnerId: 'partner-starbucks',
    partnerName: 'Starbucks',
    partnerLogo: '/images/partners/starbucks.svg',
    name: 'Frappuccino',
    description: 'Buzlu Frappuccino',
    image: '🧋',
    category: 'coffee',
    stock: 100,
    expiryHours: 72,
    sponsorId: 'sponsor-garanti',
    sponsorName: 'Garanti BBVA',
    isActive: true,
    isPremium: false,
  },
  {
    id: 'gift-6',
    partnerId: 'partner-migros',
    partnerName: 'Migros',
    partnerLogo: '/images/partners/migros.svg',
    name: 'Eti Browni',
    description: 'Eti Browni Intense çikolatalı kek',
    image: '🍰',
    category: 'chocolate',
    stock: 180,
    expiryHours: 72,
    isActive: true,
    isPremium: false,
  },
  {
    id: 'gift-7',
    partnerId: 'partner-dr',
    partnerName: 'D&R',
    partnerLogo: '/images/partners/dr.svg',
    name: 'Simyacı',
    description: 'Paulo Coelho - Simyacı',
    image: '📚',
    category: 'book',
    stock: 60,
    expiryHours: 72,
    isActive: true,
    isPremium: false,
  },
  {
    id: 'gift-8',
    partnerId: 'partner-starbucks',
    partnerName: 'Starbucks',
    partnerLogo: '/images/partners/starbucks.svg',
    name: 'Cheesecake',
    description: 'New York Cheesecake dilimi',
    image: '🍰',
    category: 'food',
    stock: 45,
    expiryHours: 72,
    sponsorId: 'sponsor-turkcell',
    sponsorName: 'Turkcell',
    isActive: true,
    isPremium: true,
  },
  {
    id: 'gift-9',
    partnerId: 'partner-ciceksepeti',
    partnerName: 'Çiçeksepeti',
    partnerLogo: '/images/partners/ciceksepeti.svg',
    name: 'Kır Çiçeği Buketi',
    description: 'Renkli kır çiçekleri buketi',
    image: '💐',
    category: 'flower',
    stock: 30,
    expiryHours: 72,
    isActive: true,
    isPremium: true,
  },
  // ── Starbucks ek ürünler (toplam 5) ──
  {
    id: 'gift-10',
    partnerId: 'partner-starbucks',
    partnerName: 'Starbucks',
    partnerLogo: '/images/partners/starbucks.svg',
    name: 'Türk Kahvesi',
    description: 'Geleneksel Türk Kahvesi',
    image: '☕',
    category: 'coffee',
    stock: 120,
    expiryHours: 72,
    isActive: true,
    isPremium: false,
  },
  {
    id: 'gift-11',
    partnerId: 'partner-starbucks',
    partnerName: 'Starbucks',
    partnerLogo: '/images/partners/starbucks.svg',
    name: 'Cookie',
    description: 'Çikolata parçalı kurabiye',
    image: '🍪',
    category: 'food',
    stock: 90,
    expiryHours: 72,
    isActive: true,
    isPremium: false,
  },
  // ── Migros ek ürünler (toplam 5) ──
  {
    id: 'gift-12',
    partnerId: 'partner-migros',
    partnerName: 'Migros',
    partnerLogo: '/images/partners/migros.svg',
    name: 'Dondurma',
    description: 'Algida Magnum Classic',
    image: '🍦',
    category: 'food',
    stock: 160,
    expiryHours: 72,
    isActive: true,
    isPremium: false,
  },
  {
    id: 'gift-13',
    partnerId: 'partner-migros',
    partnerName: 'Migros',
    partnerLogo: '/images/partners/migros.svg',
    name: 'Meyve Suyu',
    description: 'Cappy taze sıkılmış portakal',
    image: '🧃',
    category: 'food',
    stock: 200,
    expiryHours: 72,
    isActive: true,
    isPremium: false,
  },
  {
    id: 'gift-14',
    partnerId: 'partner-migros',
    partnerName: 'Migros',
    partnerLogo: '/images/partners/migros.svg',
    name: 'Çikolatalı Gofret',
    description: 'Ülker Çikolatalı Gofret',
    image: '🍫',
    category: 'chocolate',
    stock: 250,
    expiryHours: 72,
    isActive: true,
    isPremium: false,
  },
  {
    id: 'gift-15',
    partnerId: 'partner-migros',
    partnerName: 'Migros',
    partnerLogo: '/images/partners/migros.svg',
    name: 'Kahve Paketi',
    description: 'Nescafé Gold filtre kahve',
    image: '☕',
    category: 'coffee',
    stock: 80,
    expiryHours: 72,
    sponsorId: 'sponsor-turkcell',
    sponsorName: 'Turkcell',
    isActive: true,
    isPremium: true,
  },
  // ── D&R ek ürünler (toplam 5) ──
  {
    id: 'gift-16',
    partnerId: 'partner-dr',
    partnerName: 'D&R',
    partnerLogo: '/images/partners/dr.svg',
    name: 'Defter',
    description: 'Moleskine classic defter',
    image: '📓',
    category: 'book',
    stock: 70,
    expiryHours: 72,
    isActive: true,
    isPremium: false,
  },
  {
    id: 'gift-17',
    partnerId: 'partner-dr',
    partnerName: 'D&R',
    partnerLogo: '/images/partners/dr.svg',
    name: 'Kalem Seti',
    description: 'Staedtler renkli kalem seti',
    image: '✏️',
    category: 'book',
    stock: 55,
    expiryHours: 72,
    isActive: true,
    isPremium: false,
  },
  {
    id: 'gift-18',
    partnerId: 'partner-dr',
    partnerName: 'D&R',
    partnerLogo: '/images/partners/dr.svg',
    name: 'Puzzle',
    description: '1000 parça İstanbul manzarası',
    image: '🧩',
    category: 'experience',
    stock: 40,
    expiryHours: 72,
    sponsorId: 'sponsor-garanti',
    sponsorName: 'Garanti BBVA',
    isActive: true,
    isPremium: true,
  },
  // ── Çiçeksepeti ek ürünler (toplam 5) ──
  {
    id: 'gift-19',
    partnerId: 'partner-ciceksepeti',
    partnerName: 'Çiçeksepeti',
    partnerLogo: '/images/partners/ciceksepeti.svg',
    name: 'Orkide',
    description: 'Beyaz orkide saksı çiçeği',
    image: '🪻',
    category: 'flower',
    stock: 25,
    expiryHours: 72,
    isActive: true,
    isPremium: false,
  },
  {
    id: 'gift-20',
    partnerId: 'partner-ciceksepeti',
    partnerName: 'Çiçeksepeti',
    partnerLogo: '/images/partners/ciceksepeti.svg',
    name: 'Çikolata Kutusu',
    description: 'Godiva 12li pralin kutusu',
    image: '🎁',
    category: 'chocolate',
    stock: 35,
    expiryHours: 72,
    sponsorId: 'sponsor-garanti',
    sponsorName: 'Garanti BBVA',
    isActive: true,
    isPremium: true,
  },
  {
    id: 'gift-21',
    partnerId: 'partner-ciceksepeti',
    partnerName: 'Çiçeksepeti',
    partnerLogo: '/images/partners/ciceksepeti.svg',
    name: 'Ayçiçeği',
    description: 'Taze sarı ayçiçeği buketi',
    image: '🌻',
    category: 'flower',
    stock: 40,
    expiryHours: 72,
    isActive: true,
    isPremium: false,
  },
];

const now = new Date();
const hourMs = 3600000;

export const MOCK_GIFT_ACTIONS: GiftAction[] = [
  {
    id: 'action-1',
    giftId: 'gift-1',
    gift: MOCK_GIFTS[0],
    senderId: 'user-2',
    senderName: 'Ayşe',
    receiverId: 'user-1',
    receiverPhone: '+905551234567',
    receiverName: 'Coşkun',
    note: 'Bugün aklıma geldin',
    status: 'pending',
    redeemCode: 'TKR-A1B2C3',
    createdAt: new Date(now.getTime() - 2 * hourMs).toISOString(),
    expiresAt: new Date(now.getTime() + 70 * hourMs).toISOString(),
  },
  {
    id: 'action-2',
    giftId: 'gift-2',
    gift: MOCK_GIFTS[1],
    senderId: 'user-3',
    senderName: 'Mehmet',
    receiverId: 'user-1',
    receiverPhone: '+905551234567',
    receiverName: 'Coşkun',
    note: 'Sebepsiz',
    status: 'pending',
    redeemCode: 'TKR-D4E5F6',
    createdAt: new Date(now.getTime() - 5 * hourMs).toISOString(),
    expiresAt: new Date(now.getTime() + 67 * hourMs).toISOString(),
  },
  {
    id: 'action-3',
    giftId: 'gift-3',
    gift: MOCK_GIFTS[2],
    senderId: 'user-1',
    senderName: 'Coşkun',
    receiverId: 'user-2',
    receiverPhone: '+905559876543',
    receiverName: 'Ayşe',
    note: 'Geçen hafta için',
    status: 'claimed',
    redeemCode: 'TKR-G7H8I9',
    createdAt: new Date(now.getTime() - 48 * hourMs).toISOString(),
    expiresAt: new Date(now.getTime() + 24 * hourMs).toISOString(),
    claimedAt: new Date(now.getTime() - 24 * hourMs).toISOString(),
    branchId: 'b6',
    branchName: 'D&R Cevahir',
  },
  {
    id: 'action-4',
    giftId: 'gift-4',
    gift: MOCK_GIFTS[3],
    senderId: 'user-1',
    senderName: 'Coşkun',
    receiverPhone: '+905557778899',
    receiverName: 'Selin',
    note: 'İyi ki varsın',
    status: 'expired',
    redeemCode: 'TKR-J1K2L3',
    createdAt: new Date(now.getTime() - 96 * hourMs).toISOString(),
    expiresAt: new Date(now.getTime() - 24 * hourMs).toISOString(),
  },
  {
    id: 'action-5',
    giftId: 'gift-5',
    gift: MOCK_GIFTS[4],
    senderId: 'user-2',
    senderName: 'Ayşe',
    receiverPhone: '+905554443322',
    receiverName: 'Ali',
    status: 'social_pool',
    redeemCode: 'TKR-M4N5O6',
    createdAt: new Date(now.getTime() - 120 * hourMs).toISOString(),
    expiresAt: new Date(now.getTime() - 48 * hourMs).toISOString(),
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    type: 'gift_received',
    title: 'Yeni Hediye!',
    message: 'Ayşe sana bir Latte ısmarladı ☕',
    isRead: false,
    createdAt: new Date(now.getTime() - 2 * hourMs).toISOString(),
    actionId: 'action-1',
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    type: 'gift_received',
    title: 'Yeni Hediye!',
    message: 'Mehmet sana bir Tadelle Çikolata gönderdi 🍫',
    isRead: false,
    createdAt: new Date(now.getTime() - 5 * hourMs).toISOString(),
    actionId: 'action-2',
  },
  {
    id: 'notif-3',
    userId: 'user-1',
    type: 'gift_redeemed',
    title: 'Hediyeni Aldı!',
    message: 'Ayşe hediyeni aldı! ✓',
    isRead: true,
    createdAt: new Date(now.getTime() - 24 * hourMs).toISOString(),
    actionId: 'action-3',
  },
  {
    id: 'notif-4',
    userId: 'user-1',
    type: 'gift_to_pool',
    title: 'Askıda Jest',
    message: "Selin hediyesini zamanında alamamıştı ama bir öğrenciyi mutlu etti 💛",
    isRead: true,
    createdAt: new Date(now.getTime() - 20 * hourMs).toISOString(),
    actionId: 'action-4',
  },
];

export const MOCK_FRAUD_FLAGS: FraudFlag[] = [
  {
    id: 'fraud-1',
    userId: 'user-999',
    type: 'looping',
    severity: 'medium',
    description: 'user-999 ve user-998 arasında 5 gün boyunca karşılıklı hediye gönderimi tespit edildi',
    createdAt: new Date(now.getTime() - 48 * hourMs).toISOString(),
    resolved: false,
  },
  {
    id: 'fraud-2',
    userId: 'user-888',
    type: 'emulator',
    severity: 'high',
    description: 'Cihaz emülatör olarak tanımlandı (BlueStacks)',
    createdAt: new Date(now.getTime() - 12 * hourMs).toISOString(),
    resolved: false,
  },
  {
    id: 'fraud-3',
    userId: 'user-777',
    type: 'fake_gps',
    severity: 'high',
    description: 'Konum 2 dakika içinde 150km değişti (fiziksel olarak imkansız)',
    createdAt: new Date(now.getTime() - 6 * hourMs).toISOString(),
    resolved: true,
  },
];

// ==========================================
// PAZAR ARAŞTIRMASI - YENİ MOCK VERİLER
// ==========================================

// Haftalık Drop verileri
export const MOCK_WEEKLY_DROP: WeeklyDrop = {
  id: 'drop-1',
  title: 'İYİ Kİ Perşembesi',
  description: 'Bu haftanın sınırlı sayıda jestleri! İlk gelen kapar.',
  gifts: [MOCK_GIFTS[0], MOCK_GIFTS[1], MOCK_GIFTS[3]],
  totalStock: 50,
  claimedCount: 23,
  startsAt: (() => {
    const d = new Date();
    d.setHours(10, 0, 0, 0);
    return d.toISOString();
  })(),
  endsAt: (() => {
    const d = new Date();
    d.setHours(22, 0, 0, 0);
    return d.toISOString();
  })(),
  isActive: true,
};

// Topluluk kampanyaları
export const MOCK_COMMUNITIES: CommunityPool[] = [
  {
    id: 'comm-1',
    name: 'İTÜ Kampüs',
    emoji: '🎓',
    description: 'İTÜ öğrencileri arası jest havuzu',
    type: 'university',
    memberCount: 342,
    giftsShared: 89,
    isActive: true,
    requirement: '.itu.edu.tr e-posta',
  },
  {
    id: 'comm-2',
    name: 'Boğaziçi Kahve Kulübü',
    emoji: '☕',
    description: 'Boğaziçi Üniversitesi sınav haftası kahve havuzu',
    type: 'university',
    memberCount: 218,
    giftsShared: 56,
    isActive: true,
    requirement: '.boun.edu.tr e-posta',
  },
  {
    id: 'comm-3',
    name: 'Kadıköy Mahallesi',
    emoji: '🏘️',
    description: 'Kadıköy sakinleri arası ikramlar',
    type: 'neighborhood',
    memberCount: 156,
    giftsShared: 34,
    isActive: true,
  },
  {
    id: 'comm-4',
    name: 'Tech Meetup İstanbul',
    emoji: '💻',
    description: 'Yazılımcılar arası jest ağı',
    type: 'event',
    memberCount: 89,
    giftsShared: 22,
    isActive: true,
  },
];

// 1+1 İkram teklifleri
export const MOCK_PLUS_ONE_OFFERS: PlusOneOffer[] = [
  {
    id: 'po-1',
    giftId: 'gift-1',
    giftName: 'Latte',
    giftImage: '☕',
    sponsorName: 'Garanti BBVA',
    message: 'Beraber gidin, senin kahven de Garanti BBVA sponsorluğunda!',
    isActive: true,
  },
  {
    id: 'po-2',
    giftId: 'gift-5',
    giftName: 'Frappuccino',
    giftImage: '🧋',
    sponsorName: 'Turkcell',
    message: 'Arkadaşınla git, ikinci Frappuccino Turkcell\'den hediye!',
    isActive: true,
  },
];

// Kullanıcının kazandığı rozetler (demo)
export const MOCK_USER_ACHIEVEMENTS: Achievement[] = [
  { ...ACHIEVEMENTS_LIST[0], unlockedAt: '2026-03-15T10:00:00Z' },
  { ...ACHIEVEMENTS_LIST[4], unlockedAt: '2026-03-16T14:30:00Z' },
  { ...ACHIEVEMENTS_LIST[8], unlockedAt: '2026-03-28T09:00:00Z' },
];
